### ISSUE TITLE
列表项目中的代码框会挡住嘉然

### ISSUE THREAD

**Issue by skykeyjoker** [q19980722/Typora-theme-jiaran#12]
列表中的代码框会挡住嘉然，正文则显示正常。
正文（显示正常）：
![1](https://user-images.githubusercontent.com/17134346/133930762-15b827ba-b207-41c7-8e5e-095ce582f390.jpg)
列表（显示异常）：
![2](https://user-images.githubusercontent.com/17134346/133930765-98221779-f542-4c34-be9d-778ab15d5089.jpg)

**Comment by q19980722** [comment]
暂时无法彻底解决这个问题。我觉得可以通过限制代码框的宽度解决。

**Comment by skykeyjoker** [comment]
= =修复不修复我倒是无所谓

**Comment by skykeyjoker** [comment]
修复不修复我倒无所谓= =
感觉影响不大

**Comment by Yurzi** [comment]
或许是z-index的值的问题？

**Comment by skykeyjoker** [comment]
> 或许是z-index的值的问题？

大概是这样的，但没有找到怎么修改=。=

**Comment by skykeyjoker** [comment]
也有可能是列表的background-color的问题

**Comment by Yurzi** [comment]
我修好了 哈哈哈！！<img src="http://res.yurzi.top/emote/jiaran/jiarenmen.png" width="50px" height="50px">

我发现其实不在列表区里的代码块.md-fences的background值是继承的，也就是继承了#write的background的设置。同时#write中的attachment设置的是fixed,所以其实透明效果是假的透明效果，只是在同样的位置重新渲染了一次然然的图片

然后是列表区的代码块，虽然也是继承，但是继承的列表的background设置.所以只能显示已经设置的background-color。可是就算给列表的background设置成inherit也不行，不知道为什么。<img src="http://res.yurzi.top/emote/jiaran/chuitousangqi.png" width="50px" height="50px">

于是我只能很不优雅的在.md-fences中重新设置一遍background的相关属性，将其和#write中的设置一致。就解决了这个问题
<img src="http://res.yurzi.top/emote/jiaran/anxiang.png" width="50px" height="50px">

同时我发现卡片模式下的段落等元素的width也是继承，导致了卡片模式下的列表中的内容会长出来.

**Comment by skykeyjoker** [comment]
> 我修好了 哈哈哈！！<img alt="" width="50px" height="50px" src="https://camo.githubusercontent.com/8799a4ded7d7e49b4e50a9368eff3d478565ea946ee78713d1feb4e20c9a09fe/687474703a2f2f7265732e7975727a692e746f702f656d6f74652f6a696172616e2f6a696172656e6d656e2e706e67">
> 
> 我发现其实不在列表区里的代码块.md-fences的background值是继承的，也就是继承了#write的background的设置。同时#write中的attachment设置的是fixed,所以其实透明效果是假的透明效果，只是在同样的位置重新渲染了一次然然的图片
> 
> 然后是列表区的代码块，虽然也是继承，但是继承的列表的background设置.所以只能显示已经设置的background-color。可是就算给列表的background设置成inherit也不行，不知道为什么。<img alt="" width="50px" height="50px" src="https://camo.githubusercontent.com/063f4e61cd03db02ebd614d54251eaa88d9bcb299896e543be6acd2c4916437e/687474703a2f2f7265732e7975727a692e746f702f656d6f74652f6a696172616e2f63687569746f7573616e6771692e706e67">
> 
> 于是我只能很不优雅的在.md-fences中重新设置一遍background的相关属性，将其和#write中的设置一致。就解决了这个问题
> <img alt="" width="50px" height="50px" src="https://camo.githubusercontent.com/fc07c3c4b615525fa5cf0ac21726b52c3682976ec126153ea6acb85db2f0d32b/687474703a2f2f7265732e7975727a692e746f702f656d6f74652f6a696172616e2f616e7869616e672e706e67">
> 
> 同时我发现卡片模式下的段落等元素的width也是继承，导致了卡片模式下的列表中的内容会长出来.

巨龙！
