### ISSUE TITLE
左键滑动选中没有显示（或者是颜色不清晰？）

### ISSUE THREAD

**Issue by umnooob** [q19980722/Typora-theme-jiaran#14]
![image](https://user-images.githubusercontent.com/41941089/133954703-e7482d20-8ed5-41a2-9f7b-58f3ad765fdf.png)
![image](https://user-images.githubusercontent.com/41941089/133954728-09939d15-2569-4bd0-81d5-d283e8af6289.png)

**Comment by q19980722** [comment]
不太明白你说的问题，是选中没有底色还是什么意思。 你截图中上面的是选中的，下面是没选中的吗，我看着挺正常啊

**Comment by umnooob** [comment]
> 不太明白你说的问题，是选中没有底色还是什么意思。 你截图中上面的是选中的，下面是没选中的吗，我看着挺正常啊

是选中没有底色，上面的是github主题，下面是jiaran card主题

**Comment by q19980722** [comment]
好的明白了，我待会检查一下代码，谢谢

**Comment by skykeyjoker** [comment]
这里的问题是颜色不太清晰，标准化颜色之后，主题设置里面的一些颜色被用混了，我正在改= 。=

**Comment by q19980722** [comment]
> 这里的问题是颜色不太清晰，标准化颜色之后，主题设置里面的一些颜色被用混了，我正在改= 。=

有一些差别很小的颜色被归为一种了，要不然颜色太多了也不好配色。

**Comment by q19980722** [comment]
> 这里的问题是颜色不太清晰，标准化颜色之后，主题设置里面的一些颜色被用混了，我正在改= 。=

有一些差别很小的颜色被归为一种了，要不然颜色太多了也不好配色。

**Comment by skykeyjoker** [comment]
已修改
