### ISSUE TITLE
未使用全屏时，插入图片显示不全

### ISSUE THREAD

**Issue by RyaoChengfeng** [q19980722/Typora-theme-jiaran#15]
使用jiaran主题时：
全屏时：
![2021-09-22_05-52](https://user-images.githubusercontent.com/69711608/134252850-53bb4ff1-7aea-4f4a-b9a4-2bffad386bee.png)
未全屏时：
![2021-09-22_05-56_1](https://user-images.githubusercontent.com/69711608/134253254-3937b499-3965-4c28-9e17-5ed0ff9b9c89.png)

使用vue主题时：
![2021-09-22_05-56](https://user-images.githubusercontent.com/69711608/134253190-77f67ab3-5d2a-4eea-b4aa-db733eea64b0.png)

**Comment by q19980722** [comment]
可能是页面小了，因为没有缩放吧，我这边测试如果页面没有图片大的话插入的时候会有一个缩放的提示。

**Comment by RyaoChengfeng** [comment]
> 可能是页面小了，因为没有缩放吧，我这边测试如果页面没有图片大的话插入的时候会有一个缩放的提示。

这个"缩放的提示"是typora自己的逻辑吗？我在linux版和windows64的最新版typora上均复现了使用jiaran时图片没有缩放的问题，而在其他theme上却没有出现这个问题

**Comment by Yurzi** [comment]
已解决
