### ISSUE TITLE
typora奇怪渲染问题(windows)

### ISSUE THREAD

**Issue by skykeyjoker** [q19980722/Typora-theme-jiaran#16]

**Comment by skykeyjoker** [comment]
颜色标准化之后，使用变量名代替颜色，在例如代码框渲染时会遇到问题（windows）
![QQ截图20210922214713](https://user-images.githubusercontent.com/17134346/134357001-272f4b28-eb4f-4c00-8566-18893bca4bd7.jpg)
。
正常情况下（第二种实现）：
![QQ图片20210922215342](https://user-images.githubusercontent.com/17134346/134357054-2c23026b-6104-4dd7-90fd-0bba67ec2047.png)
非正常情况下（变量名）：
![QQ图片20210922215338](https://user-images.githubusercontent.com/17134346/134357117-ec234e05-1f37-488f-b8a7-026e996e84c7.png)

**Comment by q19980722** [comment]
我这边没有这种情况发生。。

**Comment by skykeyjoker** [comment]
> 我这边没有这种情况发生。。

win平台么，win平台的话版本号是多少= =

**Comment by q19980722** [comment]
> > 我这边没有这种情况发生。。
> 
> win平台么，win平台的话版本号是多少= =

mac的，Win的我不知道

**Comment by skykeyjoker** [comment]
> > > 我这边没有这种情况发生。。
> > 
> > 
> > win平台么，win平台的话版本号是多少= =
> 
> mac的，Win的我不知道

可能是win平台的问题= =
有点想创死typora了捏

**Comment by skykeyjoker** [comment]
破案了，我声明变量的时候用了一个中文的冒号。。。
这下贝极星了。。。
