### ISSUE TITLE
标题使用`** XXX **`加粗时，侧边栏没有同时渲染加粗

### ISSUE THREAD

**Issue by RyaoChengfeng** [q19980722/Typora-theme-jiaran#39]
侧边栏指左侧的大纲
![image](https://user-images.githubusercontent.com/69711608/151684629-1993030c-dd9e-4fee-97e6-72b592532cba.png)
比如在未加粗时
![image](https://user-images.githubusercontent.com/69711608/151684564-75f87234-4529-4696-a3ad-1eb8c6b38b1a.png)
此时，侧边栏字体为
![image](https://user-images.githubusercontent.com/69711608/151684569-41a63b63-f700-40c2-a54a-c22347e259a0.png)
而加粗后
![image](https://user-images.githubusercontent.com/69711608/151684572-cdc0f23e-6013-4ebe-95a2-2216620cd11a.png)
字体反而变为未加粗状态
![image](https://user-images.githubusercontent.com/69711608/151684585-18078799-b5e0-4f00-a9cc-cf11090f6e38.png)

**Comment by skykeyjoker** [comment]
```
#typora-sidebar {
  color: #404040;
  /*font-weight: bold;*/  /* Bold title Error */
}
```css
注释处代码会引起该错误。

**Comment by skykeyjoker** [comment]
#40 已修复
