### ISSUE TITLE
右下角然然的显示 bug

### ISSUE THREAD

**Issue by Hakureirm** [q19980722/Typora-theme-jiaran#5]
由上到下滑动，然然的一部分就会贴在代码块上面了，只有再滑动回去才能消除![](https://i.loli.net/2021/09/18/dZw2T8vMecsiJUa.png)

**Comment by skykeyjoker** [comment]
这个bug是每次都能复现嘛？
很奇怪，我这边不能复现= =
不过我有一些文件会遇到另外一个然然显示的bug：然然有时候会被代码框覆盖住。
初步怀疑是代码框的样式问题= =
不过我不一定能修好，可能要靠作者来帮一下忙了

**Comment by q19980722** [comment]
个人猜测是在堆叠的时候渲染发生的问题，前端技术不太懂。 所以在#write中加入z-index=1，确实可以解决这个bug。至于原理我不懂哈。

**Comment by skykeyjoker** [comment]
我也不懂前端。。。
不过嘉心糖还是好强捏

**Comment by Hakureirm** [comment]
> 个人猜测是在堆叠的时候渲染发生的问题，前端技术不太懂。 所以在#write中加入z-index=1，确实可以解决这个bug。至于原理我不懂哈。

经过我测试，在#write中加入z-index=0的情况下，然然上下滑动显示就正常了，设为1及以上然然会卡住，只有改变页面大小时才会刷新

**Comment by skykeyjoker** [comment]
> > 个人猜测是在堆叠的时候渲染发生的问题，前端技术不太懂。 所以在#write中加入z-index=1，确实可以解决这个bug。至于原理我不懂哈。
> 
> 经过我测试，在#write中加入z-index=0的情况下，然然上下滑动显示就正常了，设为1及以上然然会卡住，只有改变页面大小时才会刷新

额。。。看起来每个人都有不同的解决方案。。。估计改成0问题都可以解决。。。
